using System;
using System.Collections.Generic;
using System.Globalization;

namespace DragonDen.ModManager.Services.Localization;

/// <summary>
/// In-app localization: en, zh-CN, zh-TW, ru. Switch via Settings → Language.
/// UI text uses Loc.T("key"); call ApplyLanguage on pages when LanguageChanged fires.
/// </summary>
public static class Loc
{
    public const string En = "en";
    public const string ZhCn = "zh-CN";
    public const string ZhTw = "zh-TW";
    public const string Ru = "ru";

    private static string _current = En;
    private static readonly Dictionary<string, Dictionary<string, string>> Catalogs = new();

    public static string CurrentLanguage => _current;
    public static event Action? LanguageChanged;

    static Loc()
    {
        Catalogs[En] = BuildEnglish();
        Catalogs[ZhCn] = BuildZhCn();
        Catalogs[ZhTw] = BuildZhTw();
        Catalogs[Ru] = BuildRussian();
    }

    public static void InitializeFromConfig()
    {
        var cfgLang = App.Config?.UI?.Language?.Trim() ?? "";
        if (string.IsNullOrEmpty(cfgLang))
        {
            var culture = CultureInfo.CurrentUICulture.Name;
            if (culture.StartsWith("zh-CN", StringComparison.OrdinalIgnoreCase) ||
                culture.Equals("zh-Hans", StringComparison.OrdinalIgnoreCase) ||
                culture.StartsWith("zh-Hans", StringComparison.OrdinalIgnoreCase))
                cfgLang = ZhCn;
            else if (culture.StartsWith("zh-TW", StringComparison.OrdinalIgnoreCase) ||
                     culture.StartsWith("zh-HK", StringComparison.OrdinalIgnoreCase) ||
                     culture.StartsWith("zh-MO", StringComparison.OrdinalIgnoreCase) ||
                     culture.Equals("zh-Hant", StringComparison.OrdinalIgnoreCase) ||
                     culture.StartsWith("zh-Hant", StringComparison.OrdinalIgnoreCase))
                cfgLang = ZhTw;
            else if (culture.StartsWith("ru", StringComparison.OrdinalIgnoreCase))
                cfgLang = Ru;
            else
                cfgLang = En;
        }
        SetLanguage(cfgLang, save: false);
    }

    public static void SetLanguage(string lang, bool save = true)
    {
        lang = Normalize(lang);
        if (_current == lang && save) return;
        _current = lang;
        if (save && App.Config?.UI != null)
        {
            App.Config.UI.Language = lang;
            try { Config.Save(Config.GetDefaultConfigPath()); } catch { /* ignore */ }
        }
        try { LanguageChanged?.Invoke(); } catch { /* ignore */ }
    }

    public static string T(string key)
    {
        if (Catalogs.TryGetValue(_current, out var dict) && dict.TryGetValue(key, out var v) && !string.IsNullOrEmpty(v))
            return v;
        if (Catalogs.TryGetValue(En, out var en) && en.TryGetValue(key, out var ev))
            return ev;
        return key;
    }

    public static string T(string key, params object[] args)
    {
        var fmt = T(key);
        try { return string.Format(fmt, args); } catch { return fmt; }
    }

    public static string Normalize(string lang)
    {
        lang = (lang ?? "").Trim();
        if (lang.Equals("zh", StringComparison.OrdinalIgnoreCase) ||
            lang.Equals("zh-CN", StringComparison.OrdinalIgnoreCase) ||
            lang.Equals("zh-Hans", StringComparison.OrdinalIgnoreCase) ||
            lang.StartsWith("zh-Hans", StringComparison.OrdinalIgnoreCase))
            return ZhCn;
        if (lang.Equals("zh-TW", StringComparison.OrdinalIgnoreCase) ||
            lang.Equals("zh-HK", StringComparison.OrdinalIgnoreCase) ||
            lang.Equals("zh-Hant", StringComparison.OrdinalIgnoreCase) ||
            lang.StartsWith("zh-Hant", StringComparison.OrdinalIgnoreCase))
            return ZhTw;
        if (lang.Equals("en", StringComparison.OrdinalIgnoreCase) ||
            lang.StartsWith("en-", StringComparison.OrdinalIgnoreCase))
            return En;
        if (lang.Equals("ru", StringComparison.OrdinalIgnoreCase) ||
            lang.StartsWith("ru-", StringComparison.OrdinalIgnoreCase))
            return Ru;
        return string.IsNullOrEmpty(lang) ? En : lang;
    }

    private static Dictionary<string, string> BuildEnglish() => new(StringComparer.OrdinalIgnoreCase)
    {
        ["App.Title"] = "Dragon Den Mod Manager",
        ["Nav.Browse"] = "Browse Mods",
        ["Nav.Installed"] = "Installed Mods",
        ["Nav.Settings"] = "Settings",
        ["Nav.Collections"] = "Collections",
        ["Nav.CollectionsProfiles"] = "Collections Profiles",
        ["Common.Refresh"] = "Refresh",
        ["Common.Clear"] = "Clear",
        ["Common.Cancel"] = "Cancel",
        ["Common.Close"] = "Close",
        ["Common.Save"] = "Save",
        ["Common.Browse"] = "Browse...",
        ["Common.Install"] = "Install",
        ["Common.Uninstall"] = "Uninstall",
        ["Common.Search"] = "Search mods or type @Author...",
        ["Common.Page"] = "Page",
        ["Common.Prev"] = "◀ Prev",
        ["Common.Next"] = "Next ▶",
        ["Common.Show"] = "Show",
        ["Common.Later"] = "Later",
        ["Common.Copy"] = "Click to copy",
        ["Common.Open"] = "Open",
        ["Common.Loading"] = "Loading results...",
        ["Browse.HideFeatured"] = "Hide Featured",
        ["Browse.HideAds"] = "Hide Contains Ads",
        ["Browse.HideAI"] = "Hide Contains AI",
        ["Browse.HideInstalled"] = "Hide Installed",
        ["Browse.FikaOnly"] = "Fika Comp Only",
        ["Browse.SortRecent"] = "Most recent",
        ["Browse.SortNewest"] = "Newest published",
        ["Browse.SortDownloads"] = "Most downloads",
        ["Browse.Downloads"] = "Downloads",
        ["Browse.Queued"] = "Queued",
        ["Browse.ModPage"] = "Mod Page",
        ["Browse.OpenModPage"] = "Open Mod Page",
        ["Browse.CopyPageUrl"] = "Copy Page URL",
        ["Browse.OpenThumbnail"] = "Open Thumbnail",
        ["Browse.CopyGuid"] = "Copy GUID",
        ["Installed.UpdateAll"] = "Update All",
        ["Installed.EnableAll"] = "Enable All",
        ["Installed.DisableAll"] = "Disable All",
        ["Installed.ClientFolder"] = "Client Folder",
        ["Installed.ServerFolder"] = "Server Folder",
        ["Installed.UninstallAll"] = "Uninstall All",
        ["Installed.SortAlpha"] = "Alphabetical (A→Z)",
        ["Installed.SortNewest"] = "Newest installed",
        ["Installed.SortOldest"] = "Oldest installed",
        ["Installed.SortEnabled"] = "Enabled First",
        ["Installed.SortDisabled"] = "Disabled First",
        ["Installed.SortUpdates"] = "Updates first",
        ["Installed.HideDisabled"] = "Hide Disabled mods",
        ["Installed.Toggle"] = "Toggle enable/disable",
        ["Installed.DisabledTip"] = "This mod is disabled, toggle checkmark to enable.",
        ["Installed.ModDisabled"] = "Mod Disabled",
        ["Installed.NotManager"] = "This mod was not installed with Mod Manager",
        ["Installed.NotSupported"] = "Not Supported",
        ["Installed.UpdateMod"] = "Update Mod",
        ["Installed.UpdateTip"] = "Click to update to latest version.",
        ["Installed.ChangeVersion"] = "Change Version",
        ["Installed.CustomInstall"] = "Custom Install",
        ["Installed.Installed"] = "Installed",
        ["Installed.Files"] = "Files",
        ["Installed.LatestPublished"] = "Latest published",
        ["Installed.ListFiles"] = "List Files",
        ["Installed.EditConfigs"] = "Edit Configs",
        ["Installed.Empty"] = "No mods found.",
        ["Installed.EmptyHint"] = "Install something from Browse Mods, or click Refresh to scan your SPT folder.",
        ["Installed.Loading"] = "Loading installed mods...",
        ["Installed.Scanning"] = "Scanning mods...",
        ["Installed.Showing"] = "Showing {0} of {1} installed",
        ["Settings.SptFolder"] = "SPT Folder",
        ["Settings.SptFolderHint"] = "Pick the game root. It will auto-detect the spt version and configure plugins and mods folders.",
        ["Settings.NoFolder"] = "No folder selected.",
        ["Settings.DataFolder"] = "Data Folder",
        ["Settings.DataFolderHint"] = "Pick a folder where downloads and temp extracts will be done.",
        ["Settings.DataFolderEmpty"] = "(will use data folder in manager folder if empty)",
        ["Settings.ResetDefault"] = "Reset to Default",
        ["Settings.ModPaths"] = "Mod Paths",
        ["Settings.ClientSubpath"] = "Client mods subpath",
        ["Settings.ServerSubpath"] = "Server mods subpath",
        ["Settings.FinalPaths"] = "Final mod folder paths",
        ["Settings.ForgeToken"] = "Forge API Token",
        ["Settings.ForgeTokenHint"] = "Used to fetch mod info from Forge. Your token is stored locally.",
        ["Settings.UI"] = "UI",
        ["Settings.ExpertTip"] = "Expert mode. Only enable if you know what you are doing.",
        ["Settings.ExpertMode"] = "Expert mode (skip startup and install warnings)",
        ["Settings.Language"] = "Language",
        ["Settings.ClearCache"] = "Clear Cache",
        ["Settings.ClearTemp"] = "Clear Temp Files",
        ["Settings.ClearLogs"] = "Clear Log Files",
        ["Settings.Saved"] = "All settings have been saved successfully.",
        ["Dialog.Token.Title"] = "Forge Token (optional)",
        ["Dialog.Token.Prompt"] = "Forge API token (optional). Read-only scope is enough. You can skip and set it later in Settings.",
        ["Dialog.Token.Placeholder"] = "Paste token here (read-only scope)",
        ["Dialog.Token.Save"] = "Save Token",
        ["Dialog.Token.OpenHelp"] = "Open Forge API Tokens page",
        ["Dialog.Token.ReadOnly"] = "Make sure the token has only Read permissions checked.",
        ["Dialog.FirstRun.Title"] = "Select SPT Folder",
        ["Dialog.FirstRun.Body"] = "Select the install root containing BepInEx and SPT_Runtime. The app looks for SPT.Server.exe under SPT_Runtime or in the root.",
        ["Dialog.FirstRun.Hint"] = "Tip: root should contain BepInEx and SPT_Runtime (SPT.Server.exe is inside SPT_Runtime).",
        ["Dialog.FirstRun.Select"] = "Select SPT Folder",
        ["Dialog.ConfirmUninstall.Title"] = "Uninstall Mod",
        ["Dialog.ConfirmUninstall.Body"] = "Do you want to uninstall this mod?",
        ["Dialog.ConfirmUninstall.Detail"] = "The mod's files will be removed from your SPT folder.",
        ["Dialog.Deps.Title"] = "Dependencies required",
        ["Dialog.Deps.Optional"] = "(optional)",
        ["Dialog.Deps.Hint"] = "Choose your option wisely...",
        ["Dialog.Deps.With"] = "Install mod + dependencies",
        ["Dialog.Deps.Without"] = "Install without dependencies",
        ["Dialog.Queue.Title"] = "Installation Queue",
        ["Dialog.Queue.Completed"] = "Completed",
        ["Dialog.Queue.ClearCompleted"] = "Clear Completed",
        ["Dialog.Queue.Current"] = "Current:",
        ["Dialog.Queue.Queue"] = "Queue:",
        ["Dialog.FirstInstall.Title"] = "First Install",
        ["Dialog.FirstInstall.Read"] = "Read the Forge page before installing.",
        ["Dialog.FirstInstall.Check"] = "Check SPT version, requirements, and install notes.",
        ["Dialog.FirstInstall.Backup"] = "Back up your SPT folder.",
        ["Dialog.FirstInstall.Deps"] = "Confirm dependencies and incompatibilities.",
        ["Dialog.FirstInstall.Spt40"] = "Only SPT 4.0 and up is supported.",
        ["Dialog.FirstInstall.AfterOpen"] = "Install available after opening the mod page",
        ["Dialog.FirstInstall.Install"] = "Install Mod",
        ["Dialog.Update.Title"] = "Update Available",
        ["Dialog.Update.Body"] = "A newer version of Dragon Den Mod Manager is available.",
        ["Dialog.Update.Changelog"] = "Changelog",
        ["Dialog.Update.ShowPage"] = "Show Update Page",
        ["Dialog.Update.Later"] = "I'll install later",
        ["Dialog.Version.Title"] = "Select a Version",
        ["Dialog.Config.Title"] = "Config Editor",
        ["Dialog.Config.Hint"] = "Select a config to edit • ESC closes this window",
        ["Dialog.Config.Modified"] = "• Modified",
        ["Dialog.Config.Reset"] = "Reset Changes",
        ["Dialog.Files.Tip"] = "Tip: double clicking will open them. (or use config editor for built-in editor)",
        ["Dialog.Files.Esc"] = "ESC key closes this window.",
        ["Dialog.Alpha.Title"] = "Welcome and Alpha Notice",
        ["Dialog.Alpha.Disclaimer"] = "Disclaimer",
        ["Dialog.Alpha.Support"] = "Support Policy",
        ["Dialog.Alpha.Before"] = "Before You Continue",
        ["Dialog.Alpha.Community"] = "Community",
        ["Dialog.Alpha.Agree"] = "I Understand and Agree",
        ["Dialog.Alpha.Disagree"] = "I Disagree",
        ["Collections.Soon"] = "This feature will be added in the near future.",
        ["TitleBar.Feedback"] = "Report Issues and Feedback Here",
        ["KoFi"] = "Support me on Ko-fi",
        ["Notify.CategoriesFailed"] = "Couldn't load categories.",
        ["Notify.RefreshFailed"] = "Couldn't refresh mod cache or Forge data.",
        ["Notify.SearchFailed"] = "Couldn't complete search query.",
        ["Notify.Copied"] = "Copied to clipboard.",
        ["Notify.CopyFailed"] = "Couldn't copy to clipboard.",
        ["Notify.InvalidSpt"] = "SPT.Server.exe not found. Select the install root with BepInEx and SPT_Runtime.",
        ["Notify.SettingsSaved"] = "Settings saved.",
        ["Notify.CacheCleared"] = "Cache cleared.",
        ["Notify.FolderInvalid"] = "Selected folder doesn't exist.",
        ["Notify.TokenSkipped"] = "No token entered. Forge will be accessed anonymously (read-only).",
        ["Notify.TokenSaved"] = "Token saved.",
        ["Notify.TokenInvalid"] = "Token validation failed.",

        ["Settings.SptDetected"] = "Detected SPT {0}",
        ["Settings.SptDetectedUnknown"] = "Detected SPT (version unknown)",
        ["Settings.SptNotFound"] = "SPT.Server.exe not found in this folder.",
        ["Settings.Hide"] = "Hide",
        ["Fika.Compatible"] = "Fika compatible",
        ["Fika.Incompatible"] = "Fika incompatible",
        ["Fika.CompatibleInstalled"] = "Fika compatible (installed)",
        ["Fika.IncompatibleInstalled"] = "Fika incompatible (installed)",
        ["Fika.CompatibleLatest"] = "Fika compatible (latest)",
        ["Fika.IncompatibleLatest"] = "Fika incompatible (latest)",
        ["Installed.Uncategorized"] = "(Uncategorized)",
        ["Installed.CustomInstallLabel"] = "Custom Install",
        ["Notify.DataFolderReset"] = "Data folder reset",
        ["Notify.DataFolderResetBody"] = "Data folder restored to default location.",
        ["Notify.DataFolderChanged"] = "Data folder changed",
        ["Notify.DataFolderChangedBody"] = "Data folder updated successfully.",
        ["Notify.InvalidFolder"] = "Invalid folder",
        ["Notify.FolderNotExist"] = "Selected folder does not exist.",
        ["Notify.SptFolderChanged"] = "SPT folder changed",
        ["Notify.SptFolderChangedBody"] = "SPT folder updated successfully.",
        ["Dialog.SelectDataFolder"] = "Select a new data folder.",
        ["Dialog.SelectSptFolder"] = "Select SPT folder.",
        ["Browse.Category"] = "Category",
        ["Browse.Version"] = "Version",
        ["Browse.Fika"] = "Fika",
        ["Common.Hide"] = "Hide",
        ["Status.Ready"] = "Ready",
        ["Status.Syncing"] = "Syncing with Forge…",
        ["Status.Installing"] = "Installing…",
    };

    private static Dictionary<string, string> BuildZhCn() => new(StringComparer.OrdinalIgnoreCase)
    {
        ["App.Title"] = "Dragon Den 模组管理器",
        ["Nav.Browse"] = "浏览模组",
        ["Nav.Installed"] = "已安装模组",
        ["Nav.Settings"] = "设置",
        ["Nav.Collections"] = "合集",
        ["Nav.CollectionsProfiles"] = "合集配置",
        ["Common.Refresh"] = "刷新",
        ["Common.Clear"] = "清除",
        ["Common.Cancel"] = "取消",
        ["Common.Close"] = "关闭",
        ["Common.Save"] = "保存",
        ["Common.Browse"] = "浏览…",
        ["Common.Install"] = "安装",
        ["Common.Uninstall"] = "卸载",
        ["Common.Search"] = "搜索模组，或输入 @作者名…",
        ["Common.Page"] = "页",
        ["Common.Prev"] = "◀ 上一页",
        ["Common.Next"] = "下一页 ▶",
        ["Common.Show"] = "显示",
        ["Common.Later"] = "稍后",
        ["Common.Copy"] = "点击复制",
        ["Common.Open"] = "打开",
        ["Common.Loading"] = "正在加载结果…",
        ["Browse.HideFeatured"] = "隐藏精选",
        ["Browse.HideAds"] = "隐藏含广告",
        ["Browse.HideAI"] = "隐藏含 AI",
        ["Browse.HideInstalled"] = "隐藏已安装",
        ["Browse.FikaOnly"] = "仅 Fika 兼容",
        ["Browse.SortRecent"] = "最近更新",
        ["Browse.SortNewest"] = "最新发布",
        ["Browse.SortDownloads"] = "下载最多",
        ["Browse.Downloads"] = "下载量",
        ["Browse.Queued"] = "排队中",
        ["Browse.ModPage"] = "模组页面",
        ["Browse.OpenModPage"] = "打开模组页面",
        ["Browse.CopyPageUrl"] = "复制页面链接",
        ["Browse.OpenThumbnail"] = "打开缩略图",
        ["Browse.CopyGuid"] = "复制 GUID",
        ["Installed.UpdateAll"] = "全部更新",
        ["Installed.EnableAll"] = "全部启用",
        ["Installed.DisableAll"] = "全部禁用",
        ["Installed.ClientFolder"] = "客户端目录",
        ["Installed.ServerFolder"] = "服务端目录",
        ["Installed.UninstallAll"] = "全部卸载",
        ["Installed.SortAlpha"] = "名称 (A→Z)",
        ["Installed.SortNewest"] = "最近安装",
        ["Installed.SortOldest"] = "最早安装",
        ["Installed.SortEnabled"] = "已启用优先",
        ["Installed.SortDisabled"] = "已禁用优先",
        ["Installed.SortUpdates"] = "有更新优先",
        ["Installed.HideDisabled"] = "隐藏已禁用",
        ["Installed.Toggle"] = "切换启用/禁用",
        ["Installed.DisabledTip"] = "此模组已禁用，勾选以启用。",
        ["Installed.ModDisabled"] = "模组已禁用",
        ["Installed.NotManager"] = "此模组不是通过本管理器安装的",
        ["Installed.NotSupported"] = "不支持",
        ["Installed.UpdateMod"] = "更新模组",
        ["Installed.UpdateTip"] = "点击更新到最新版本。",
        ["Installed.ChangeVersion"] = "更换版本",
        ["Installed.CustomInstall"] = "自定义安装",
        ["Installed.Installed"] = "已安装",
        ["Installed.Files"] = "文件",
        ["Installed.LatestPublished"] = "最新发布",
        ["Installed.ListFiles"] = "文件列表",
        ["Installed.EditConfigs"] = "编辑配置",
        ["Installed.Empty"] = "未找到模组。",
        ["Installed.EmptyHint"] = "请从「浏览模组」安装，或点击「刷新」扫描 SPT 目录。",
        ["Installed.Loading"] = "正在加载已安装模组…",
        ["Installed.Scanning"] = "正在扫描模组…",
        ["Installed.Showing"] = "显示 {0} / {1} 个已安装",
        ["Settings.SptFolder"] = "SPT 目录",
        ["Settings.SptFolderHint"] = "选择游戏安装根目录。将自动检测 SPT 版本并配置插件与模组路径。",
        ["Settings.NoFolder"] = "尚未选择文件夹。",
        ["Settings.DataFolder"] = "数据目录",
        ["Settings.DataFolderHint"] = "选择下载与临时解压所用的文件夹。",
        ["Settings.DataFolderEmpty"] = "（留空则使用管理器目录下的 data 文件夹）",
        ["Settings.ResetDefault"] = "恢复默认",
        ["Settings.ModPaths"] = "模组路径",
        ["Settings.ClientSubpath"] = "客户端模组相对路径",
        ["Settings.ServerSubpath"] = "服务端模组相对路径",
        ["Settings.FinalPaths"] = "最终模组目录路径",
        ["Settings.ForgeToken"] = "Forge API 令牌",
        ["Settings.ForgeTokenHint"] = "用于从 Forge 获取模组信息。令牌保存在本地。",
        ["Settings.UI"] = "界面",
        ["Settings.ExpertTip"] = "专家模式：仅在你清楚后果时启用。",
        ["Settings.ExpertMode"] = "专家模式（跳过启动与安装警告）",
        ["Settings.Language"] = "语言",
        ["Settings.ClearCache"] = "清除缓存",
        ["Settings.ClearTemp"] = "清除临时文件",
        ["Settings.ClearLogs"] = "清除日志",
        ["Settings.Saved"] = "所有设置已成功保存。",
        ["Dialog.Token.Title"] = "需要 Forge 令牌（可跳过）",
        ["Dialog.Token.Prompt"] = "Forge API 令牌（可选）。只读权限即可。可跳过，稍后在设置中填写。",
        ["Dialog.Token.Placeholder"] = "在此粘贴令牌（只读权限即可）",
        ["Dialog.Token.Save"] = "保存令牌",
        ["Dialog.Token.OpenHelp"] = "打开 Forge 令牌页面",
        ["Dialog.Token.ReadOnly"] = "令牌可选。若填写请仅勾选 Read 只读权限。",
        ["Dialog.FirstRun.Title"] = "选择 SPT 目录",
        ["Dialog.FirstRun.Body"] = "请选择含 BepInEx 与 SPT_Runtime 的安装根目录。程序会在根目录或 SPT_Runtime 下查找 SPT.Server.exe。",
        ["Dialog.FirstRun.Hint"] = "提示：根目录应含 BepInEx 与 SPT_Runtime（SPT.Server.exe 在 SPT_Runtime 内）。",
        ["Dialog.FirstRun.Select"] = "选择 SPT 文件夹",
        ["Dialog.ConfirmUninstall.Title"] = "卸载模组",
        ["Dialog.ConfirmUninstall.Body"] = "确定要卸载此模组吗？",
        ["Dialog.ConfirmUninstall.Detail"] = "模组文件将从 SPT 目录中删除。",
        ["Dialog.Deps.Title"] = "需要依赖",
        ["Dialog.Deps.Optional"] = "（可选）",
        ["Dialog.Deps.Hint"] = "请谨慎选择…",
        ["Dialog.Deps.With"] = "安装模组及依赖",
        ["Dialog.Deps.Without"] = "仅安装模组（不含依赖）",
        ["Dialog.Queue.Title"] = "安装队列",
        ["Dialog.Queue.Completed"] = "已完成",
        ["Dialog.Queue.ClearCompleted"] = "清除已完成",
        ["Dialog.Queue.Current"] = "当前：",
        ["Dialog.Queue.Queue"] = "队列：",
        ["Dialog.FirstInstall.Title"] = "首次安装",
        ["Dialog.FirstInstall.Read"] = "安装前请先阅读 Forge 模组页面。",
        ["Dialog.FirstInstall.Check"] = "确认 SPT 版本、依赖与安装说明。",
        ["Dialog.FirstInstall.Backup"] = "请先备份你的 SPT 目录。",
        ["Dialog.FirstInstall.Deps"] = "确认依赖与兼容性。",
        ["Dialog.FirstInstall.Spt40"] = "仅支持 SPT 4.0 及以上。",
        ["Dialog.FirstInstall.AfterOpen"] = "打开模组页面后可安装",
        ["Dialog.FirstInstall.Install"] = "安装模组",
        ["Dialog.Update.Title"] = "发现更新",
        ["Dialog.Update.Body"] = "Dragon Den 模组管理器有新版本可用。",
        ["Dialog.Update.Changelog"] = "更新日志",
        ["Dialog.Update.ShowPage"] = "打开更新页面",
        ["Dialog.Update.Later"] = "稍后再说",
        ["Dialog.Version.Title"] = "选择版本",
        ["Dialog.Config.Title"] = "配置编辑器",
        ["Dialog.Config.Hint"] = "选择要编辑的配置 • ESC 关闭窗口",
        ["Dialog.Config.Modified"] = "• 已修改",
        ["Dialog.Config.Reset"] = "重置更改",
        ["Dialog.Files.Tip"] = "提示：双击可打开文件（或使用配置编辑器）。",
        ["Dialog.Files.Esc"] = "按 ESC 关闭此窗口。",
        ["Dialog.Alpha.Title"] = "欢迎与内测说明",
        ["Dialog.Alpha.Disclaimer"] = "免责声明",
        ["Dialog.Alpha.Support"] = "支持策略",
        ["Dialog.Alpha.Before"] = "继续之前",
        ["Dialog.Alpha.Community"] = "社区",
        ["Dialog.Alpha.Agree"] = "我已了解并同意",
        ["Dialog.Alpha.Disagree"] = "不同意",
        ["Collections.Soon"] = "此功能将在后续版本中加入。",
        ["TitleBar.Feedback"] = "反馈问题",
        ["KoFi"] = "在 Ko-fi 上支持我",
        ["Notify.CategoriesFailed"] = "无法加载分类。",
        ["Notify.RefreshFailed"] = "无法刷新模组缓存或 Forge 数据。",
        ["Notify.SearchFailed"] = "无法完成搜索。",
        ["Notify.Copied"] = "已复制到剪贴板。",
        ["Notify.CopyFailed"] = "无法复制到剪贴板。",
        ["Notify.InvalidSpt"] = "未找到 SPT.Server.exe。请选择含 BepInEx 与 SPT_Runtime 的安装根目录。",
        ["Notify.SettingsSaved"] = "设置已保存。",
        ["Notify.CacheCleared"] = "缓存已清除。",
        ["Notify.FolderInvalid"] = "所选文件夹不存在。",
        ["Notify.TokenSkipped"] = "未填写令牌，将以匿名方式访问 Forge（只读）。可稍后在设置中填写。",
        ["Notify.TokenSaved"] = "令牌已保存。",
        ["Notify.TokenInvalid"] = "令牌验证失败。",

        ["Settings.SptDetected"] = "已检测到 SPT {0}",
        ["Settings.SptDetectedUnknown"] = "已检测到 SPT（版本未知）",
        ["Settings.SptNotFound"] = "在此文件夹中找不到 SPT.Server.exe。",
        ["Settings.Hide"] = "隐藏",
        ["Fika.Compatible"] = "Fika 兼容",
        ["Fika.Incompatible"] = "Fika 不兼容",
        ["Fika.CompatibleInstalled"] = "Fika 兼容（已安装）",
        ["Fika.IncompatibleInstalled"] = "Fika 不兼容（已安装）",
        ["Fika.CompatibleLatest"] = "Fika 兼容（最新版）",
        ["Fika.IncompatibleLatest"] = "Fika 不兼容（最新版）",
        ["Installed.Uncategorized"] = "（未分类）",
        ["Installed.CustomInstallLabel"] = "自定义安装",
        ["Notify.DataFolderReset"] = "数据目录已重置",
        ["Notify.DataFolderResetBody"] = "数据目录已恢复为默认位置。",
        ["Notify.DataFolderChanged"] = "数据目录已更改",
        ["Notify.DataFolderChangedBody"] = "数据目录已成功更新。",
        ["Notify.InvalidFolder"] = "无效文件夹",
        ["Notify.FolderNotExist"] = "所选文件夹不存在。",
        ["Notify.SptFolderChanged"] = "SPT 目录已更改",
        ["Notify.SptFolderChangedBody"] = "SPT 目录已成功更新。",
        ["Dialog.SelectDataFolder"] = "选择新的数据文件夹。",
        ["Dialog.SelectSptFolder"] = "选择 SPT 文件夹。",
        ["Browse.Category"] = "分类",
        ["Browse.Version"] = "版本",
        ["Browse.Fika"] = "Fika",
        ["Common.Hide"] = "隐藏",
        ["Status.Ready"] = "就绪",
        ["Status.Syncing"] = "正在同步 Forge…",
        ["Status.Installing"] = "正在安装…",
    };

    private static Dictionary<string, string> BuildZhTw() => new(StringComparer.OrdinalIgnoreCase)
    {
        ["App.Title"] = "Dragon Den 模組管理器",
        ["Nav.Browse"] = "瀏覽模組",
        ["Nav.Installed"] = "已安裝模組",
        ["Nav.Settings"] = "設定",
        ["Nav.Collections"] = "合集",
        ["Nav.CollectionsProfiles"] = "合集設定",
        ["Common.Refresh"] = "重新整理",
        ["Common.Clear"] = "清除",
        ["Common.Cancel"] = "取消",
        ["Common.Close"] = "關閉",
        ["Common.Save"] = "儲存",
        ["Common.Browse"] = "瀏覽…",
        ["Common.Install"] = "安裝",
        ["Common.Uninstall"] = "解除安裝",
        ["Common.Search"] = "搜尋模組，或輸入 @作者名…",
        ["Common.Page"] = "頁",
        ["Common.Prev"] = "◀ 上一頁",
        ["Common.Next"] = "下一頁 ▶",
        ["Common.Show"] = "顯示",
        ["Common.Later"] = "稍後",
        ["Common.Copy"] = "點擊複製",
        ["Common.Open"] = "開啟",
        ["Common.Loading"] = "正在載入結果…",
        ["Browse.HideFeatured"] = "隱藏精選",
        ["Browse.HideAds"] = "隱藏含廣告",
        ["Browse.HideAI"] = "隱藏含 AI",
        ["Browse.HideInstalled"] = "隱藏已安裝",
        ["Browse.FikaOnly"] = "僅 Fika 相容",
        ["Browse.SortRecent"] = "最近更新",
        ["Browse.SortNewest"] = "最新發布",
        ["Browse.SortDownloads"] = "下載最多",
        ["Browse.Downloads"] = "下載量",
        ["Browse.Queued"] = "排隊中",
        ["Browse.ModPage"] = "模組頁面",
        ["Browse.OpenModPage"] = "開啟模組頁面",
        ["Browse.CopyPageUrl"] = "複製頁面連結",
        ["Browse.OpenThumbnail"] = "開啟縮圖",
        ["Browse.CopyGuid"] = "複製 GUID",
        ["Installed.UpdateAll"] = "全部更新",
        ["Installed.EnableAll"] = "全部啟用",
        ["Installed.DisableAll"] = "全部停用",
        ["Installed.ClientFolder"] = "用戶端目錄",
        ["Installed.ServerFolder"] = "伺服端目錄",
        ["Installed.UninstallAll"] = "全部解除安裝",
        ["Installed.SortAlpha"] = "名稱 (A→Z)",
        ["Installed.SortNewest"] = "最近安裝",
        ["Installed.SortOldest"] = "最早安裝",
        ["Installed.SortEnabled"] = "已啟用優先",
        ["Installed.SortDisabled"] = "已停用優先",
        ["Installed.SortUpdates"] = "有更新優先",
        ["Installed.HideDisabled"] = "隱藏已停用",
        ["Installed.Toggle"] = "切換啟用/停用",
        ["Installed.DisabledTip"] = "此模組已停用，勾選以啟用。",
        ["Installed.ModDisabled"] = "模組已停用",
        ["Installed.NotManager"] = "此模組不是透過本管理器安裝的",
        ["Installed.NotSupported"] = "不支援",
        ["Installed.UpdateMod"] = "更新模組",
        ["Installed.UpdateTip"] = "點擊更新到最新版本。",
        ["Installed.ChangeVersion"] = "更換版本",
        ["Installed.CustomInstall"] = "自訂安裝",
        ["Installed.Installed"] = "已安裝",
        ["Installed.Files"] = "檔案",
        ["Installed.LatestPublished"] = "最新發布",
        ["Installed.ListFiles"] = "檔案列表",
        ["Installed.EditConfigs"] = "編輯設定",
        ["Installed.Empty"] = "未找到模組。",
        ["Installed.EmptyHint"] = "請從「瀏覽模組」安裝，或點擊「重新整理」掃描 SPT 目錄。",
        ["Installed.Loading"] = "正在載入已安裝模組…",
        ["Installed.Scanning"] = "正在掃描模組…",
        ["Installed.Showing"] = "顯示 {0} / {1} 個已安裝",
        ["Settings.SptFolder"] = "SPT 目錄",
        ["Settings.SptFolderHint"] = "選擇遊戲安裝根目錄。將自動偵測 SPT 版本並設定外掛與模組路徑。",
        ["Settings.NoFolder"] = "尚未選擇資料夾。",
        ["Settings.DataFolder"] = "資料目錄",
        ["Settings.DataFolderHint"] = "選擇下載與暫存解壓所用的資料夾。",
        ["Settings.DataFolderEmpty"] = "（留空則使用管理器目錄下的 data 資料夾）",
        ["Settings.ResetDefault"] = "恢復預設",
        ["Settings.ModPaths"] = "模組路徑",
        ["Settings.ClientSubpath"] = "用戶端模組相對路徑",
        ["Settings.ServerSubpath"] = "伺服端模組相對路徑",
        ["Settings.FinalPaths"] = "最終模組目錄路徑",
        ["Settings.ForgeToken"] = "Forge API 權杖",
        ["Settings.ForgeTokenHint"] = "用於從 Forge 取得模組資訊。權杖保存在本機。",
        ["Settings.UI"] = "介面",
        ["Settings.ExpertTip"] = "專家模式：僅在你清楚後果時啟用。",
        ["Settings.ExpertMode"] = "專家模式（跳過啟動與安裝警告）",
        ["Settings.Language"] = "語言",
        ["Settings.ClearCache"] = "清除快取",
        ["Settings.ClearTemp"] = "清除暫存檔",
        ["Settings.ClearLogs"] = "清除日誌",
        ["Settings.Saved"] = "所有設定已成功儲存。",
        ["Dialog.Token.Title"] = "需要 Forge 權杖（可跳過）",
        ["Dialog.Token.Prompt"] = "Forge API 權杖（可選）。唯讀權限即可。可跳過，稍後在設定中填寫。",
        ["Dialog.Token.Placeholder"] = "在此貼上權杖（唯讀權限即可）",
        ["Dialog.Token.Save"] = "儲存權杖",
        ["Dialog.Token.OpenHelp"] = "開啟 Forge 權杖頁面",
        ["Dialog.Token.ReadOnly"] = "權杖可選。若填寫請僅勾選 Read 唯讀權限。",
        ["Dialog.FirstRun.Title"] = "選擇 SPT 目錄",
        ["Dialog.FirstRun.Body"] = "請選擇含 BepInEx 與 SPT_Runtime 的安裝根目錄。程式會在根目錄或 SPT_Runtime 下尋找 SPT.Server.exe。",
        ["Dialog.FirstRun.Hint"] = "提示：根目錄應含 BepInEx 與 SPT_Runtime（SPT.Server.exe 在 SPT_Runtime 內）。",
        ["Dialog.FirstRun.Select"] = "選擇 SPT 資料夾",
        ["Dialog.ConfirmUninstall.Title"] = "解除安裝模組",
        ["Dialog.ConfirmUninstall.Body"] = "確定要解除安裝此模組嗎？",
        ["Dialog.ConfirmUninstall.Detail"] = "模組檔案將從 SPT 目錄中刪除。",
        ["Dialog.Deps.Title"] = "需要相依套件",
        ["Dialog.Deps.Optional"] = "（可選）",
        ["Dialog.Deps.Hint"] = "請謹慎選擇…",
        ["Dialog.Deps.With"] = "安裝模組及相依套件",
        ["Dialog.Deps.Without"] = "僅安裝模組（不含相依）",
        ["Dialog.Queue.Title"] = "安裝佇列",
        ["Dialog.Queue.Completed"] = "已完成",
        ["Dialog.Queue.ClearCompleted"] = "清除已完成",
        ["Dialog.Queue.Current"] = "目前：",
        ["Dialog.Queue.Queue"] = "佇列：",
        ["Dialog.FirstInstall.Title"] = "首次安裝",
        ["Dialog.FirstInstall.Read"] = "安裝前請先閱讀 Forge 模組頁面。",
        ["Dialog.FirstInstall.Check"] = "確認 SPT 版本、需求與安裝說明。",
        ["Dialog.FirstInstall.Backup"] = "請先備份你的 SPT 目錄。",
        ["Dialog.FirstInstall.Deps"] = "確認相依與相容性。",
        ["Dialog.FirstInstall.Spt40"] = "僅支援 SPT 4.0 及以上。",
        ["Dialog.FirstInstall.AfterOpen"] = "開啟模組頁面後可安裝",
        ["Dialog.FirstInstall.Install"] = "安裝模組",
        ["Dialog.Update.Title"] = "發現更新",
        ["Dialog.Update.Body"] = "Dragon Den 模組管理器有新版本可用。",
        ["Dialog.Update.Changelog"] = "更新日誌",
        ["Dialog.Update.ShowPage"] = "開啟更新頁面",
        ["Dialog.Update.Later"] = "稍後再說",
        ["Dialog.Version.Title"] = "選擇版本",
        ["Dialog.Config.Title"] = "設定編輯器",
        ["Dialog.Config.Hint"] = "選擇要編輯的設定 • ESC 關閉視窗",
        ["Dialog.Config.Modified"] = "• 已修改",
        ["Dialog.Config.Reset"] = "重設變更",
        ["Dialog.Files.Tip"] = "提示：雙擊可開啟檔案（或使用設定編輯器）。",
        ["Dialog.Files.Esc"] = "按 ESC 關閉此視窗。",
        ["Dialog.Alpha.Title"] = "歡迎與測試說明",
        ["Dialog.Alpha.Disclaimer"] = "免責聲明",
        ["Dialog.Alpha.Support"] = "支援策略",
        ["Dialog.Alpha.Before"] = "繼續之前",
        ["Dialog.Alpha.Community"] = "社群",
        ["Dialog.Alpha.Agree"] = "我已了解並同意",
        ["Dialog.Alpha.Disagree"] = "不同意",
        ["Collections.Soon"] = "此功能將在後續版本中加入。",
        ["TitleBar.Feedback"] = "回報問題",
        ["KoFi"] = "在 Ko-fi 上支持我",
        ["Notify.CategoriesFailed"] = "無法載入分類。",
        ["Notify.RefreshFailed"] = "無法重新整理模組快取或 Forge 資料。",
        ["Notify.SearchFailed"] = "無法完成搜尋。",
        ["Notify.Copied"] = "已複製到剪貼簿。",
        ["Notify.CopyFailed"] = "無法複製到剪貼簿。",
        ["Notify.InvalidSpt"] = "找不到 SPT.Server.exe。請選擇含 BepInEx 與 SPT_Runtime 的安裝根目錄。",
        ["Notify.SettingsSaved"] = "設定已儲存。",
        ["Notify.CacheCleared"] = "快取已清除。",
        ["Notify.FolderInvalid"] = "所選資料夾不存在。",
        ["Notify.TokenSkipped"] = "未填寫權杖，將以匿名方式存取 Forge（唯讀）。可稍後在設定中填寫。",
        ["Notify.TokenSaved"] = "權杖已儲存。",
        ["Notify.TokenInvalid"] = "權杖驗證失敗。",

        ["Settings.SptDetected"] = "已偵測到 SPT {0}",
        ["Settings.SptDetectedUnknown"] = "已偵測到 SPT（版本未知）",
        ["Settings.SptNotFound"] = "在此資料夾中找不到 SPT.Server.exe。",
        ["Settings.Hide"] = "隱藏",
        ["Fika.Compatible"] = "Fika 相容",
        ["Fika.Incompatible"] = "Fika 不相容",
        ["Fika.CompatibleInstalled"] = "Fika 相容（已安裝）",
        ["Fika.IncompatibleInstalled"] = "Fika 不相容（已安裝）",
        ["Fika.CompatibleLatest"] = "Fika 相容（最新版）",
        ["Fika.IncompatibleLatest"] = "Fika 不相容（最新版）",
        ["Installed.Uncategorized"] = "（未分類）",
        ["Installed.CustomInstallLabel"] = "自訂安裝",
        ["Notify.DataFolderReset"] = "資料目錄已重設",
        ["Notify.DataFolderResetBody"] = "資料目錄已恢復為預設位置。",
        ["Notify.DataFolderChanged"] = "資料目錄已變更",
        ["Notify.DataFolderChangedBody"] = "資料目錄已成功更新。",
        ["Notify.InvalidFolder"] = "無效資料夾",
        ["Notify.FolderNotExist"] = "所選資料夾不存在。",
        ["Notify.SptFolderChanged"] = "SPT 目錄已變更",
        ["Notify.SptFolderChangedBody"] = "SPT 目錄已成功更新。",
        ["Dialog.SelectDataFolder"] = "選擇新的資料資料夾。",
        ["Dialog.SelectSptFolder"] = "選擇 SPT 資料夾。",
        ["Browse.Category"] = "分類",
        ["Browse.Version"] = "版本",
        ["Browse.Fika"] = "Fika",
        ["Common.Hide"] = "隱藏",
        ["Status.Ready"] = "就緒",
        ["Status.Syncing"] = "正在同步 Forge…",
        ["Status.Installing"] = "正在安裝…",
    };

    private static Dictionary<string, string> BuildRussian() => new(StringComparer.OrdinalIgnoreCase)
    {
        ["App.Title"] = "Dragon Den Мод-менеджер",
        ["Nav.Browse"] = "Обзор модов",
        ["Nav.Installed"] = "Установленные",
        ["Nav.Settings"] = "Настройки",
        ["Nav.Collections"] = "Коллекции",
        ["Nav.CollectionsProfiles"] = "Профили коллекций",
        ["Common.Refresh"] = "Обновить",
        ["Common.Clear"] = "Очистить",
        ["Common.Cancel"] = "Отмена",
        ["Common.Close"] = "Закрыть",
        ["Common.Save"] = "Сохранить",
        ["Common.Browse"] = "Обзор...",
        ["Common.Install"] = "Установить",
        ["Common.Uninstall"] = "Удалить",
        ["Common.Search"] = "Поиск модов или @Автор...",
        ["Common.Page"] = "Стр.",
        ["Common.Prev"] = "◀ Назад",
        ["Common.Next"] = "Далее ▶",
        ["Common.Show"] = "Показать",
        ["Common.Later"] = "Позже",
        ["Common.Copy"] = "Нажмите, чтобы скопировать",
        ["Common.Open"] = "Открыть",
        ["Common.Loading"] = "Загрузка результатов...",
        ["Common.Hide"] = "Скрыть",
        ["Browse.HideFeatured"] = "Скрыть избранные",
        ["Browse.HideAds"] = "Скрыть с рекламой",
        ["Browse.HideAI"] = "Скрыть с ИИ",
        ["Browse.HideInstalled"] = "Скрыть установленные",
        ["Browse.FikaOnly"] = "Только Fika",
        ["Browse.SortRecent"] = "Недавние",
        ["Browse.SortNewest"] = "Новые",
        ["Browse.SortDownloads"] = "По загрузкам",
        ["Browse.Downloads"] = "Загрузки",
        ["Browse.Queued"] = "В очереди",
        ["Browse.ModPage"] = "Страница мода",
        ["Browse.OpenModPage"] = "Открыть страницу мода",
        ["Browse.CopyPageUrl"] = "Копировать URL",
        ["Browse.OpenThumbnail"] = "Открыть превью",
        ["Browse.CopyGuid"] = "Копировать GUID",
        ["Browse.Category"] = "Категория",
        ["Browse.Version"] = "Версия",
        ["Browse.Fika"] = "Fika",
        ["Installed.UpdateAll"] = "Обновить все",
        ["Installed.EnableAll"] = "Включить все",
        ["Installed.DisableAll"] = "Отключить все",
        ["Installed.ClientFolder"] = "Клиент",
        ["Installed.ServerFolder"] = "Сервер",
        ["Installed.UninstallAll"] = "Удалить все",
        ["Installed.SortAlpha"] = "По алфавиту (А→Я)",
        ["Installed.SortNewest"] = "Недавно установленные",
        ["Installed.SortOldest"] = "Давно установленные",
        ["Installed.SortEnabled"] = "Сначала включённые",
        ["Installed.SortDisabled"] = "Сначала отключённые",
        ["Installed.SortUpdates"] = "Сначала с обновлениями",
        ["Installed.HideDisabled"] = "Скрыть отключённые",
        ["Installed.Toggle"] = "Вкл/выкл",
        ["Installed.DisabledTip"] = "Мод отключён, отметьте для включения.",
        ["Installed.ModDisabled"] = "Мод отключён",
        ["Installed.NotManager"] = "Этот мод установлен не через менеджер",
        ["Installed.NotSupported"] = "Не поддерживается",
        ["Installed.UpdateMod"] = "Обновить мод",
        ["Installed.UpdateTip"] = "Нажмите, чтобы обновить до последней версии.",
        ["Installed.ChangeVersion"] = "Сменить версию",
        ["Installed.CustomInstall"] = "Своя установка",
        ["Installed.Installed"] = "Установлено",
        ["Installed.Files"] = "Файлы",
        ["Installed.LatestPublished"] = "Последняя публикация",
        ["Installed.ListFiles"] = "Список файлов",
        ["Installed.EditConfigs"] = "Редактировать конфиги",
        ["Installed.Empty"] = "Моды не найдены.",
        ["Installed.EmptyHint"] = "Установите что-нибудь из «Обзор модов» или нажмите «Обновить» для сканирования папки SPT.",
        ["Installed.Loading"] = "Загрузка установленных модов...",
        ["Installed.Scanning"] = "Сканирование модов...",
        ["Installed.Showing"] = "Показано {0} из {1} установленных",
        ["Installed.Uncategorized"] = "(Без категории)",
        ["Installed.CustomInstallLabel"] = "Своя установка",
        ["Settings.SptFolder"] = "Папка SPT",
        ["Settings.SptFolderHint"] = "Выберите корень игры. Версия SPT определится автоматически, пути к плагинам и модам настроятся.",
        ["Settings.NoFolder"] = "Папка не выбрана.",
        ["Settings.DataFolder"] = "Папка данных",
        ["Settings.DataFolderHint"] = "Папка для загрузок и временных извлечений.",
        ["Settings.DataFolderEmpty"] = "(если пусто — используется data в папке менеджера)",
        ["Settings.ResetDefault"] = "Сбросить",
        ["Settings.ModPaths"] = "Пути модов",
        ["Settings.ClientSubpath"] = "Относительный путь клиентских модов",
        ["Settings.ServerSubpath"] = "Относительный путь серверных модов",
        ["Settings.FinalPaths"] = "Итоговые пути папок модов",
        ["Settings.ForgeToken"] = "Токен Forge API",
        ["Settings.ForgeTokenHint"] = "Для получения данных модов с Forge. Токен хранится локально.",
        ["Settings.UI"] = "Интерфейс",
        ["Settings.ExpertTip"] = "Режим эксперта. Включайте только если понимаете последствия.",
        ["Settings.ExpertMode"] = "Режим эксперта (пропуск предупреждений)",
        ["Settings.Language"] = "Язык",
        ["Settings.ClearCache"] = "Очистить кэш",
        ["Settings.ClearTemp"] = "Очистить временные файлы",
        ["Settings.ClearLogs"] = "Очистить логи",
        ["Settings.Saved"] = "Все настройки успешно сохранены.",
        ["Settings.SptDetected"] = "Обнаружен SPT {0}",
        ["Settings.SptDetectedUnknown"] = "Обнаружен SPT (версия неизвестна)",
        ["Settings.SptNotFound"] = "SPT.Server.exe не найден в этой папке.",
        ["Settings.Hide"] = "Скрыть",
        ["Fika.Compatible"] = "Совместим с Fika",
        ["Fika.Incompatible"] = "Несовместим с Fika",
        ["Fika.CompatibleInstalled"] = "Совместим с Fika (установлен)",
        ["Fika.IncompatibleInstalled"] = "Несовместим с Fika (установлен)",
        ["Fika.CompatibleLatest"] = "Совместим с Fika (последняя)",
        ["Fika.IncompatibleLatest"] = "Несовместим с Fika (последняя)",
        ["Dialog.Token.Title"] = "Токен Forge (необязательно)",
        ["Dialog.Token.Prompt"] = "Токен Forge API (необязательно). Достаточно только чтения. Можно пропустить и указать позже в Настройках.",
        ["Dialog.Token.Placeholder"] = "Вставьте токен (только чтение)",
        ["Dialog.Token.Save"] = "Сохранить токен",
        ["Dialog.Token.OpenHelp"] = "Открыть страницу токенов Forge",
        ["Dialog.Token.ReadOnly"] = "Убедитесь, что у токена отмечены только права Read.",
        ["Dialog.FirstRun.Title"] = "Выберите папку SPT",
        ["Dialog.FirstRun.Body"] = "Выберите корень установки с BepInEx и SPT_Runtime. Приложение ищет SPT.Server.exe в SPT_Runtime или в корне.",
        ["Dialog.FirstRun.Hint"] = "Подсказка: в корне должны быть BepInEx и SPT_Runtime (SPT.Server.exe внутри SPT_Runtime).",
        ["Dialog.FirstRun.Select"] = "Выбрать папку SPT",
        ["Dialog.ConfirmUninstall.Title"] = "Удалить мод",
        ["Dialog.ConfirmUninstall.Body"] = "Удалить этот мод?",
        ["Dialog.ConfirmUninstall.Detail"] = "Файлы мода будут удалены из папки SPT.",
        ["Dialog.Deps.Title"] = "Требуются зависимости",
        ["Dialog.Deps.Optional"] = "(необязательно)",
        ["Dialog.Deps.Hint"] = "Выбирайте внимательно...",
        ["Dialog.Deps.With"] = "Установить мод + зависимости",
        ["Dialog.Deps.Without"] = "Установить без зависимостей",
        ["Dialog.Queue.Title"] = "Очередь установки",
        ["Dialog.Queue.Completed"] = "Завершено",
        ["Dialog.Queue.ClearCompleted"] = "Очистить завершённые",
        ["Dialog.Queue.Current"] = "Текущий:",
        ["Dialog.Queue.Queue"] = "Очередь:",
        ["Dialog.FirstInstall.Title"] = "Первая установка",
        ["Dialog.FirstInstall.Read"] = "Прочитайте страницу мода на Forge перед установкой.",
        ["Dialog.FirstInstall.Check"] = "Проверьте версию SPT, требования и примечания.",
        ["Dialog.FirstInstall.Backup"] = "Сделайте резервную копию папки SPT.",
        ["Dialog.FirstInstall.Deps"] = "Подтвердите зависимости и несовместимости.",
        ["Dialog.FirstInstall.Spt40"] = "Поддерживается только SPT 4.0 и выше.",
        ["Dialog.FirstInstall.AfterOpen"] = "Установка доступна после открытия страницы мода",
        ["Dialog.FirstInstall.Install"] = "Установить мод",
        ["Dialog.Update.Title"] = "Доступно обновление",
        ["Dialog.Update.Body"] = "Доступна новая версия Dragon Den Mod Manager.",
        ["Dialog.Update.Changelog"] = "Список изменений",
        ["Dialog.Update.ShowPage"] = "Открыть страницу обновления",
        ["Dialog.Update.Later"] = "Установлю позже",
        ["Dialog.Version.Title"] = "Выберите версию",
        ["Dialog.Config.Title"] = "Редактор конфигов",
        ["Dialog.Config.Hint"] = "Выберите конфиг для редактирования • ESC закрывает окно",
        ["Dialog.Config.Modified"] = "• Изменено",
        ["Dialog.Config.Reset"] = "Сбросить изменения",
        ["Dialog.Files.Tip"] = "Подсказка: двойной клик откроет файл (или используйте редактор конфигов).",
        ["Dialog.Files.Esc"] = "Клавиша ESC закрывает это окно.",
        ["Dialog.Alpha.Title"] = "Добро пожаловать и уведомление об альфе",
        ["Dialog.Alpha.Disclaimer"] = "Отказ от ответственности",
        ["Dialog.Alpha.Support"] = "Политика поддержки",
        ["Dialog.Alpha.Before"] = "Перед продолжением",
        ["Dialog.Alpha.Community"] = "Сообщество",
        ["Dialog.Alpha.Agree"] = "Я понимаю и согласен",
        ["Dialog.Alpha.Disagree"] = "Не согласен",
        ["Collections.Soon"] = "Эта функция появится в ближайшее время.",
        ["TitleBar.Feedback"] = "Сообщить о проблеме / отзыв",
        ["KoFi"] = "Поддержать на Ko-fi",
        ["Notify.CategoriesFailed"] = "Не удалось загрузить категории.",
        ["Notify.RefreshFailed"] = "Не удалось обновить кэш модов или данные Forge.",
        ["Notify.SearchFailed"] = "Не удалось выполнить поиск.",
        ["Notify.Copied"] = "Скопировано в буфер обмена.",
        ["Notify.CopyFailed"] = "Не удалось скопировать.",
        ["Notify.InvalidSpt"] = "SPT.Server.exe не найден. Выберите корень с BepInEx и SPT_Runtime.",
        ["Notify.SettingsSaved"] = "Настройки сохранены.",
        ["Notify.CacheCleared"] = "Кэш очищен.",
        ["Notify.FolderInvalid"] = "Выбранная папка не существует.",
        ["Notify.TokenSkipped"] = "Токен не введён. Forge будет доступен анонимно (только чтение).",
        ["Notify.TokenSaved"] = "Токен сохранён.",
        ["Notify.TokenInvalid"] = "Проверка токена не удалась.",
        ["Notify.DataFolderReset"] = "Папка данных сброшена",
        ["Notify.DataFolderResetBody"] = "Папка данных восстановлена по умолчанию.",
        ["Notify.DataFolderChanged"] = "Папка данных изменена",
        ["Notify.DataFolderChangedBody"] = "Папка данных успешно обновлена.",
        ["Notify.InvalidFolder"] = "Неверная папка",
        ["Notify.FolderNotExist"] = "Выбранная папка не существует.",
        ["Notify.SptFolderChanged"] = "Папка SPT изменена",
        ["Notify.SptFolderChangedBody"] = "Папка SPT успешно обновлена.",
        ["Dialog.SelectDataFolder"] = "Выберите новую папку данных.",
        ["Dialog.SelectSptFolder"] = "Выберите папку SPT.",
        ["Status.Ready"] = "Готово",
        ["Status.Syncing"] = "Синхронизация с Forge…",
        ["Status.Installing"] = "Установка…",
    };
}
